### ISSUE TITLE
Union conflict?

### ISSUE THREAD

**Issue by ShenMue-dynmx** [evrhel/MatrixUtil#1] opened 2022-07-10 18:50 UTC
used release 1.0 files +GCC 12.1.0 x86_64-pc-linux-gnu+ vscode on EndeavourOS Linux x86_64:
Trying to include this lib from folder in project with cmake via:
`include_directories(${PROJECT_NAME} INTERFACE include)`
`link_directories(${PROJECT_NAME} PUBLIC include)`

And including it in main.cpp with `#include <mutil.h>` brings up this on build
![image](https://user-images.githubusercontent.com/106422460/178158042-c98d61d7-200d-43b7-9c18-0dd43a2fd6c4.png)

am I doing something wrong?

**Comment by ShenMue-dynmx** [comment] 2022-07-10 18:59
![image](https://user-images.githubusercontent.com/106422460/178158325-2d63ea41-8141-439c-b487-fe8fa37519e7.png)

something like this, i guess they dont like the b letter being repeated

**Comment by evrhel** [comment] 2022-10-26 22:33
Fixed in commit 6cf8e3ace40ddd9864cbcfd8c06329482b107091.

Caused by the union member conflict, and did not arise while compiling with MSVC.

**Closed as completed by evrhel** 2022-10-26 22:33 UTC
